<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'helveticaneuecyr' => array(
    '300' => $fontDir . '/helveticaneuecyr-300_7f37b1cff72cd84bf0ebb38a7ea19c4c',
    'normal' => $fontDir . '/helveticaneuecyr-normal_e1b5399a020b5bfa7088ecf8bbdb01e8',
    'bold' => $fontDir . '/helveticaneuecyr-bold_6053d9580c45076a5e2dbee4eaff6c1a',
    '500' => $fontDir . '/helveticaneuecyr-500_a59ebc40db73dbed333a285a75b50ad7',
  ),
  'gotham' => array(
    '900' => $fontDir . '/gotham-900_dc8635256ea64b56cc4f5ed34210e20d',
    'bold' => $fontDir . '/gotham-bold_e03b2012d6446a01c0e7aea6173390e3',
    'normal' => $fontDir . '/gotham-normal_73b63d972cb90430fe069a3b1ecd612a',
    '200' => $fontDir . '/gotham-200_dc2c177e5b32e72dd0cf8a7572750caf',
    '300' => $fontDir . '/gotham-300_cb9333240fc3911855ba2dfbd4431c2e',
    '500' => $fontDir . '/gotham-500_a16a15836bedf7c98710ce2ce70678e3',
    '100' => $fontDir . '/gotham-100_9817cbe94d7fb7c11b1cf0cb66553366',
    '800' => $fontDir . '/gotham-800_6e5584f5703a089384151e263eeab5cd',
  ),
  'gotham pro' => array(
    'bold_italic' => $fontDir . '/gotham-pro-bold-italic_d46b96dad1131a50c97acd4c2ea177d8',
    'italic' => $fontDir . '/gotham-pro-italic_e27cd55de8d6b0dd7c8ea66aedeabf3b',
    '500' => $fontDir . '/gotham-pro-500_40fc15b0df8ee3cab2045c70384214e2',
    '900_italic' => $fontDir . '/gotham-pro-900-italic_0b14e220068d9f55265d32f28360183c',
    'bold' => $fontDir . '/gotham-pro-bold_d26d195ddb1c85709adec588bcf01c58',
    '300_italic' => $fontDir . '/gotham-pro-300-italic_983464e9f6981e35b60f1e2793793ff5',
    '300' => $fontDir . '/gotham-pro-300_7806c7aebff58b7f41f2afa10ffa0d90',
    '900' => $fontDir . '/gotham-pro-900_a5be76b8d220b07b81f22ef49d5f027d',
    'normal' => $fontDir . '/gotham-pro-normal_7a509ddaf7895fcc274ea80f8be5bc3c',
    '500_italic' => $fontDir . '/gotham-pro-500-italic_093b8a5e0b70de9e412401eb59ececa6',
  ),
  'gotham pro narrow' => array(
    'bold' => $fontDir . '/gotham-pro-narrow-bold_341ef2befc9ff306121eeec3c3ce9c4d',
    '500' => $fontDir . '/gotham-pro-narrow-500_742a9c4d8f3c2016d7a0ed1b7fb5a19a',
  ),
) ?>